# Generated by Django 2.2.1 on 2019-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_content',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_published',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_title',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='diagnosticos_movil',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='diagnosticos_ordenador',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='dominio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='oportunidades_ordenador',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='orportunidades_movil',
            field=models.CharField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='porcentaje_movil',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='porcentaje_ordenador',
            field=models.CharField(default='', max_length=200),
        ),
    ]
